#!/usr/bin/env python3
# Copyright (c) 2026 Eleftherios Notas and XIOM Foundation
# SPDX-License-Identifier: MIT OR Apache-2.0
"""
xiom API documentation builder.

Walks a stdlib checkout, runs the `xiom-doc` binary over every source file and
assembles MkDocs-ready pages: one page per module plus an index.

Usage:
  python docs/build_api_docs.py --stdlib <path-to-stdlib-repo> \
      [--xiom-doc <path-to-xiom-doc>] [--out docs/api] [--tag vX.Y.Z] [--strict]

The stdlib source tree is expected at <stdlib>/xiom/<module>/**.xi. The driver
reads the stdlib release tag (or COMPILER_VERSION when present) for the page
header unless --tag is given. Output is deterministic; --strict exits non-zero
when any file fails to parse.
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

HEADING_RE = re.compile(r'^(#{1,6})\s')
MODULE_HEADING_RE = re.compile(r'^#+\s+Module\s+`?([A-Za-z0-9_.]+)`?\s*$')


def find_xiom_doc(explicit):
    if explicit:
        return explicit
    env = os.environ.get("XIOM_DOC_BIN")
    if env:
        return env
    name = "xiom-doc.exe" if os.name == "nt" else "xiom-doc"
    home = os.environ.get("XIOM_HOME")
    if home:
        candidate = Path(home) / "bin" / name
        if candidate.exists():
            return str(candidate)
    return name


def run_xiom_doc(binary, source_file):
    """Return (markdown, error_message)."""
    try:
        proc = subprocess.run(
            [binary, str(source_file)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except OSError as exc:
        return None, f"cannot run {binary}: {exc}"
    if proc.returncode != 0:
        detail = proc.stderr.decode("utf-8", errors="replace").strip()
        return None, detail or f"exit code {proc.returncode}"
    return proc.stdout.decode("utf-8", errors="replace"), None


def clean_file_output(text):
    """Normalize one file's xiom-doc output for embedding under an H2.

    Removes the per-file preamble and module wrapper headings, then demotes
    the remaining declaration headings by one level so they sit at H3 under
    the file section. Returns (body_lines, symbol_count).
    """
    cleaned = []
    for line in text.replace("\r\n", "\n").split("\n"):
        if line.startswith("# XIOM API Documentation"):
            continue
        if line.startswith("> Generated by `xiom doc`"):
            continue
        if MODULE_HEADING_RE.match(line):
            continue
        cleaned.append(line)

    body = []
    for line in cleaned:
        match = HEADING_RE.match(line)
        if match and len(match.group(1)) > 3:
            line = line[1:]
        if not line.strip() and body and not body[-1].strip():
            continue
        body.append(line)
    while body and not body[0].strip():
        body.pop(0)
    symbols = sum(1 for line in body if line.startswith("###"))
    return body, symbols


def module_sort_key(name):
    return (0, "core") if name == "core" else (1, name)


def build(stdlib_root, binary, out_dir, tag, strict):
    src_root = stdlib_root / "xiom"
    if not src_root.is_dir():
        print(f"error: no xiom/ source tree under {stdlib_root}", file=sys.stderr)
        return 2

    files = sorted(p for p in src_root.rglob("*.xi"))
    modules = {}
    failures = []
    empties = 0
    symbols = 0

    for source in files:
        module = source.relative_to(src_root).parts[0]
        text, error = run_xiom_doc(binary, source)
        if error is not None:
            failures.append((source.relative_to(stdlib_root).as_posix(), error.splitlines()[0]))
            continue
        body, count = clean_file_output(text)
        if count == 0 and not any(line.strip() for line in body):
            empties += 1
            continue
        symbols += count
        modules.setdefault(module, []).append((source.name, body, count))

    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = tag or "latest"
    index_lines = [
        "# Standard Library API",
        "",
        f"> Generated from the stdlib sources at `{stamp}` by `docs/build_api_docs.py`.",
        f"> {len(files)} source files, {len(modules)} modules, {symbols} documented symbols.",
        "",
        "| Module | Files | Symbols |",
        "|---|---|---|",
    ]
    written = 0
    for module in sorted(modules, key=module_sort_key):
        entries = sorted(modules[module])
        page = out_dir / f"{module}.md"
        lines = [
            f"# `stdlib.{module}`",
            "",
            f"> Generated from `{stamp}`. {len(entries)} source files, "
            f"{sum(c for _, _, c in entries)} documented symbols.",
            "",
        ]
        for name, body, _ in entries:
            if not body:
                continue
            lines.append(f"## `{name}`")
            lines.append("")
            lines.extend(body)
            lines.append("")
        write_text(page, "\n".join(lines).rstrip() + "\n")
        written += 1
        index_lines.append(f"| [`{module}`]({module}.md) | {len(entries)} | {sum(c for _, _, c in entries)} |")
    index_lines.append("")
    write_text(out_dir / "index.md", "\n".join(index_lines))

    print(f"modules: {written}")
    print(f"files:   {len(files)} ({empties} without public symbols)")
    print(f"symbols: {symbols}")
    print(f"failed:  {len(failures)}")
    for path, error in failures[:20]:
        print(f"  {path}: {error}")
    if failures and strict:
        return 1
    return 0


def write_text(path, text):
    with path.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def main():
    parser = argparse.ArgumentParser(description="Build stdlib API pages via xiom-doc")
    parser.add_argument("--stdlib", required=True, help="path to the stdlib repository")
    parser.add_argument("--xiom-doc", default=None, help="path to the xiom-doc binary")
    parser.add_argument("--out", default="docs/api", help="output directory (default: docs/api)")
    parser.add_argument("--tag", default=None, help="release tag stamped into page headers")
    parser.add_argument("--strict", action="store_true", help="exit non-zero on parse failures")
    args = parser.parse_args()

    binary = find_xiom_doc(args.xiom_doc)
    return build(Path(args.stdlib), binary, Path(args.out), args.tag, args.strict)


if __name__ == "__main__":
    sys.exit(main())
